version: '3'
services: 
    web:
        image: nginx:1.16-alpine
        container_name: w1
        depends_on:
            - php
        ports: 
            - "80:80"
        networks: 
            - nginx_network
        volumes: 
            - ./files/nginx/conf:/etc/nginx
            - /root/docker/php/ag:/usr/share/nginx/html
    php:
        build: ./files/php/
        container_name: w1-php
        networks: 
            - nginx_network
        volumes: 
            - /root/docker/php/ag:/www
networks: 
    nginx_network:
        external: true
        driver: bridge
